"""empty message

Revision ID: a037107da24d
Revises: 40189d7f6bd8
Create Date: 2023-03-30 13:24:47.748563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a037107da24d'
down_revision = '40189d7f6bd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('post', type_='foreignkey')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_id', sa.INTEGER(), nullable=True))

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_foreign_key('post', 'user', ['post_id'], ['id'])

    # ### end Alembic commands ###
